defmodule Arbor.MCP.Authorization.OAuthFlow do
  @moduledoc """
  OAuth 2.1 flow implementations for MCP authorization.

  This module handles the core OAuth flows:
  - Authorization Code Flow with PKCE
  - Client Credentials Flow
  - Token refresh flow
  """

  alias Arbor.MCP.Authorization.{
    ClientAssertion,
    HTTPClient,
    Issuer,
    OAuthTransactionStore,
    PKCE,
    Validator
  }

  @reserved_authorization_params ~w(
    response_type client_id redirect_uri scope state
    code_challenge code_challenge_method resource
  )
  @field_atoms %{
    "code" => :code,
    "iss" => :iss,
    "issuer" => :issuer,
    "require_issuer" => :require_issuer,
    "state" => :state,
    "state_param" => :state_param,
    "transaction_id" => :transaction_id
  }

  @type auth_params :: %{
          optional(:issuer) => String.t(),
          optional(:require_issuer) => boolean(),
          optional(:resource) => String.t() | [String.t()],
          optional(:additional_params) => map(),
          client_id: String.t(),
          redirect_uri: String.t(),
          authorization_endpoint: String.t(),
          scopes: [String.t()]
        }

  @type token_params :: %{
          optional(:client_secret) => String.t(),
          optional(:resource) => String.t() | [String.t()],
          optional(:transaction_id) => String.t(),
          code: String.t(),
          code_verifier: String.t(),
          client_id: String.t(),
          redirect_uri: String.t(),
          token_endpoint: String.t()
        }

  @type client_credentials_params :: %{
          optional(:scopes) => [String.t()],
          optional(:resource) => String.t() | [String.t()],
          client_id: String.t(),
          client_secret: String.t(),
          token_endpoint: String.t()
        }

  @type token_response :: %{
          access_token: String.t(),
          token_type: String.t(),
          expires_in: non_neg_integer() | nil,
          refresh_token: String.t() | nil,
          scope: String.t() | nil
        }

  @doc """
  Starts the OAuth 2.1 authorization code flow with PKCE.

  ## Example

      {:ok, auth_url, transaction} = OAuthFlow.start_authorization_flow(%{
        client_id: "my-client",
        redirect_uri: "http://localhost:8080/callback",
        authorization_endpoint: "https://auth.example.com/oauth/authorize",
        issuer: "https://auth.example.com",
        scopes: ["mcp:read", "mcp:write"]
      })

  The returned transaction contains the library-generated state, PKCE verifier,
  issuer, exact redirect URI, and an opaque `transaction_id`. Keep it private,
  pass it unchanged to `validate_authorization_response/2`, and pass either its
  `transaction_id` or the transaction itself through the authorization facade
  when exchanging the code.

  State is always generated by ArborMCP. A top-level `:state` is rejected, as are
  reserved OAuth parameters inside `:additional_params`; callers cannot replace
  the state, PKCE, redirect, resource, client, response-type, or scope fields.
  """
  @spec start_authorization_flow(auth_params()) ::
          {:ok, String.t(), map()} | {:error, term()}
  def start_authorization_flow(
        %{
          client_id: _client_id,
          redirect_uri: redirect_uri,
          authorization_endpoint: auth_endpoint,
          scopes: _scopes
        } = params
      ) do
    :telemetry.execute(
      [:arbor_mcp, :auth, :authorization, :started],
      %{system_time: System.system_time()},
      %{client_id: params.client_id}
    )

    with :ok <- reject_custom_state(params),
         :ok <- validate_additional_params(params),
         :ok <- Validator.validate_redirect_uri(redirect_uri),
         :ok <- Validator.validate_https_endpoint(auth_endpoint),
         :ok <- Validator.validate_resource_parameters(params) do
      # Generate PKCE challenge
      code_verifier = PKCE.generate_code_verifier()
      code_challenge = PKCE.generate_code_challenge(code_verifier)

      # State is always library-generated. Allowing an application-supplied
      # value makes entropy and reuse impossible to enforce consistently.
      state = generate_state()

      with {:ok, transaction_id} <-
             OAuthTransactionStore.register(
               state,
               Map.get(params, :issuer),
               redirect_uri,
               require_issuer: Map.get(params, :require_issuer, false)
             ) do
        # Build authorization URL only after the transaction is registered.
        query_params = build_auth_query_params(params, code_challenge, state)
        auth_url = build_url(auth_endpoint, query_params)

        state_data = %{
          transaction_id: transaction_id,
          code_verifier: code_verifier,
          state_param: state,
          issuer: Map.get(params, :issuer),
          require_issuer: Map.get(params, :require_issuer, false),
          redirect_uri: redirect_uri,
          initiated_at: DateTime.utc_now()
        }

        {:ok, auth_url, state_data}
      end
    end
  end

  @doc """
  Validates an authorization response against its recorded transaction.

  Transactions returned by `start_authorization_flow/1` are consumed atomically:
  exactly one concurrent callback can succeed. The `state` value must match.
  When the authorization response includes the RFC 9207 `iss` parameter, it must
  exactly equal the issuer recorded when the flow started. If the authorization
  server advertised `authorization_response_iss_parameter_supported: true`, the
  transaction requires `iss` to be present as well. Issuers are identifiers and
  are deliberately not URL-normalized. Validation succeeds with the authorization
  code only after all checks pass.

  Caller-constructed transaction maps without a `transaction_id` retain the 1.x
  validation behavior for compatibility, but cannot provide process-independent
  replay protection. Use the transaction returned by `start_authorization_flow/1`
  for all new code.
  """
  @spec validate_authorization_response(map(), map()) ::
          {:ok, String.t()} | {:error, term()}
  def validate_authorization_response(response, transaction)
      when is_map(response) and is_map(transaction) do
    case field(transaction, "transaction_id") do
      transaction_id when is_binary(transaction_id) ->
        OAuthTransactionStore.validate_callback(transaction_id, response)

      _legacy_transaction ->
        validate_legacy_authorization_response(response, transaction)
    end
  end

  def validate_authorization_response(_response, _transaction),
    do: {:error, :state_mismatch}

  @doc """
  Exchanges an authorization code for tokens.

  Include the `transaction_id` returned by `start_authorization_flow/1` to bind
  redemption to the validated callback and exact redirect URI. The transaction
  is marked redeemed before the network request. If the token response is lost,
  retry the complete authorization flow rather than reusing the code.
  """
  @spec exchange_code_for_token(token_params()) ::
          {:ok, token_response()} | {:error, term()}
  def exchange_code_for_token(
        %{
          code: _code,
          code_verifier: _code_verifier,
          client_id: _client_id,
          redirect_uri: _redirect_uri,
          token_endpoint: token_endpoint
        } = params
      ) do
    with :ok <- Validator.validate_https_endpoint(token_endpoint),
         :ok <- Validator.validate_resource_parameters(params),
         :ok <- PKCE.validate_verifier(params.code_verifier),
         :ok <- redeem_transaction_code(params) do
      request_body = build_token_request_body(params)

      case HTTPClient.make_token_request(token_endpoint, request_body) do
        {:ok, _} = ok ->
          :telemetry.execute(
            [:arbor_mcp, :auth, :token, :exchanged],
            %{system_time: System.system_time()},
            %{}
          )

          ok

        error ->
          error
      end
    end
  end

  @doc """
  Performs OAuth 2.1 client credentials flow.
  """
  @spec client_credentials_flow(client_credentials_params()) ::
          {:ok, token_response()} | {:error, term()}
  def client_credentials_flow(
        %{
          client_id: client_id,
          client_secret: client_secret,
          token_endpoint: token_endpoint
        } = params
      ) do
    with :ok <- Validator.validate_https_endpoint(token_endpoint),
         :ok <- Validator.validate_resource_parameters(params) do
      request_body = %{
        grant_type: "client_credentials",
        client_id: client_id,
        client_secret: client_secret
      }

      # Add optional parameters
      request_body =
        request_body
        |> maybe_add_scopes(params)
        |> Map.to_list()
        |> maybe_add_resource_params(params)

      HTTPClient.make_token_request(token_endpoint, request_body)
    end
  end

  @type jwt_credentials_params :: %{
          optional(:scopes) => [String.t()],
          optional(:resource) => String.t() | [String.t()],
          optional(:alg) => String.t(),
          optional(:kid) => String.t(),
          client_id: String.t(),
          private_key: JOSE.JWK.t(),
          token_endpoint: String.t()
        }

  @doc """
  Performs OAuth 2.1 client credentials flow with JWT client authentication (private_key_jwt).

  Uses RFC 7523 Section 2.2 client assertions instead of a client secret.
  """
  @spec client_credentials_jwt_flow(jwt_credentials_params()) ::
          {:ok, token_response()} | {:error, term()}
  def client_credentials_jwt_flow(
        %{
          client_id: client_id,
          private_key: private_key,
          token_endpoint: token_endpoint
        } = params
      ) do
    with :ok <- Validator.validate_https_endpoint(token_endpoint),
         :ok <- Validator.validate_resource_parameters(params),
         {:ok, assertion_params} <-
           ClientAssertion.build_assertion_params(
             client_id: client_id,
             token_endpoint: token_endpoint,
             private_key: private_key,
             alg: Map.get(params, :alg, "RS256"),
             kid: Map.get(params, :kid)
           ) do
      request_body =
        [{"grant_type", "client_credentials"}] ++
          assertion_params

      # Add optional parameters
      request_body =
        request_body
        |> maybe_add_scope_param(params)
        |> maybe_add_resource_params(params)

      HTTPClient.make_token_request(token_endpoint, request_body)
    end
  end

  @doc """
  Refreshes an access token using a refresh token.

  ## Options

  - `client_secret` - Client secret for confidential clients (default: nil)
  - `scope` - Space-separated scope string to request expanded scopes during refresh.
    Used for incremental scope upgrades (2025-11-25). If the authorization server
    supports it, the new token will have the expanded scope set.
  """
  @spec refresh_token(String.t(), String.t(), String.t(), keyword() | String.t() | nil) ::
          {:ok, token_response()} | {:error, term()}
  def refresh_token(refresh_token, client_id, token_endpoint, opts \\ nil)

  # Backwards-compatible: opts is a string (client_secret) or nil
  def refresh_token(refresh_token, client_id, token_endpoint, client_secret)
      when is_binary(client_secret) or is_nil(client_secret) do
    refresh_token(refresh_token, client_id, token_endpoint, client_secret: client_secret)
  end

  # New: opts is a keyword list
  def refresh_token(refresh_token, client_id, token_endpoint, opts) when is_list(opts) do
    client_secret = Keyword.get(opts, :client_secret)
    scope = Keyword.get(opts, :scope)

    with :ok <- Validator.validate_https_endpoint(token_endpoint) do
      request_body = %{
        grant_type: "refresh_token",
        refresh_token: refresh_token,
        client_id: client_id
      }

      request_body =
        if client_secret do
          Map.put(request_body, :client_secret, client_secret)
        else
          request_body
        end

      request_body =
        if scope do
          Map.put(request_body, :scope, scope)
        else
          request_body
        end

      HTTPClient.make_token_request(token_endpoint, Map.to_list(request_body))
    end
  end

  @doc """
  Initiates a full re-authorization flow with an expanded scope set.

  Used when a refresh token is not available or the server does not support
  scope upgrades via refresh. This starts a new authorization code flow
  with the combined current + additional scopes.
  """
  @spec reauthorize_with_scopes(auth_params(), [String.t()]) ::
          {:ok, String.t(), map()} | {:error, term()}
  def reauthorize_with_scopes(params, additional_scopes) do
    current_scopes = Map.get(params, :scopes, [])
    combined_scopes = Enum.uniq(current_scopes ++ additional_scopes)
    start_authorization_flow(%{params | scopes: combined_scopes})
  end

  # Private helpers

  defp build_auth_query_params(params, code_challenge, state) do
    base_params = [
      {"response_type", "code"},
      {"client_id", params.client_id},
      {"redirect_uri", params.redirect_uri},
      {"code_challenge", code_challenge},
      {"code_challenge_method", "S256"},
      {"state", state}
    ]

    # Add scope if present
    base_params =
      if params[:scopes] && length(params.scopes) > 0 do
        base_params ++ [{"scope", Enum.join(params.scopes, " ")}]
      else
        base_params
      end

    # Add resource parameters
    base_params = maybe_add_resource_params(base_params, params)

    # Add any additional parameters (prompt, access_type, etc.)
    case params[:additional_params] do
      nil -> base_params
      additional when is_map(additional) -> base_params ++ Map.to_list(additional)
      _ -> base_params
    end
  end

  defp build_token_request_body(params) do
    base_body = %{
      grant_type: "authorization_code",
      code: params.code,
      redirect_uri: params.redirect_uri,
      client_id: params.client_id,
      code_verifier: params.code_verifier
    }

    # Add client secret for confidential clients
    base_body =
      if params[:client_secret] do
        Map.put(base_body, :client_secret, params.client_secret)
      else
        base_body
      end

    base_body
    |> Map.to_list()
    |> maybe_add_resource_params(params)
  end

  defp maybe_add_scopes(request_body, %{scopes: scopes}) when is_list(scopes) do
    Map.put(request_body, :scope, Enum.join(scopes, " "))
  end

  defp maybe_add_scopes(request_body, _), do: request_body

  defp maybe_add_scope_param(params_list, %{scopes: scopes})
       when is_list(scopes) and scopes != [] do
    params_list ++ [{"scope", Enum.join(scopes, " ")}]
  end

  defp maybe_add_scope_param(params_list, _), do: params_list

  defp maybe_add_resource_params(params_list, %{resource: resource}) when is_binary(resource) do
    params_list ++ [{"resource", resource}]
  end

  defp maybe_add_resource_params(params_list, %{resource: resources}) when is_list(resources) do
    params_list ++ Enum.map(resources, &{"resource", &1})
  end

  defp maybe_add_resource_params(params_list, _), do: params_list

  defp generate_state do
    :crypto.strong_rand_bytes(32) |> Base.url_encode64(padding: false)
  end

  defp reject_custom_state(%{state: _state}), do: {:error, :custom_oauth_state_not_allowed}
  defp reject_custom_state(_params), do: :ok

  defp validate_additional_params(%{additional_params: additional}) when is_map(additional) do
    case Enum.find(
           Map.keys(additional),
           &(normalize_param_name(&1) in @reserved_authorization_params)
         ) do
      nil -> :ok
      key -> {:error, {:reserved_authorization_parameter, normalize_param_name(key)}}
    end
  end

  defp validate_additional_params(_params), do: :ok

  defp normalize_param_name(key) when is_atom(key), do: Atom.to_string(key)
  defp normalize_param_name(key) when is_binary(key), do: key
  defp normalize_param_name(key), do: inspect(key)

  defp validate_legacy_authorization_response(response, transaction) do
    code = field(response, "code")
    callback_state = field(response, "state")
    expected_state = field(transaction, "state_param")
    callback_issuer = field(response, "iss")
    expected_issuer = field(transaction, "issuer")
    require_issuer = field(transaction, "require_issuer") == true

    with :ok <- validate_state(callback_state, expected_state),
         :ok <- validate_response_issuer(callback_issuer, expected_issuer, require_issuer),
         :ok <- validate_authorization_code(code) do
      {:ok, code}
    end
  end

  defp redeem_transaction_code(params) do
    case Map.get(params, :transaction_id) do
      transaction_id when is_binary(transaction_id) ->
        OAuthTransactionStore.redeem_code(
          transaction_id,
          params.code,
          params.redirect_uri
        )

      _legacy_exchange ->
        :ok
    end
  end

  defp validate_state(callback_state, expected_state)
       when is_binary(callback_state) and is_binary(expected_state) do
    if secure_equal?(callback_state, expected_state), do: :ok, else: {:error, :state_mismatch}
  end

  defp validate_state(_callback_state, _expected_state), do: {:error, :state_mismatch}

  defp validate_response_issuer(nil, _expected_issuer, true),
    do: {:error, :missing_callback_issuer}

  defp validate_response_issuer(nil, _expected_issuer, false), do: :ok

  defp validate_response_issuer(_callback_issuer, nil, _require_issuer),
    do: {:error, :missing_expected_issuer}

  defp validate_response_issuer(callback_issuer, expected_issuer, _require_issuer) do
    Issuer.compare(expected_issuer, callback_issuer)
  end

  defp validate_authorization_code(code) when is_binary(code) and code != "", do: :ok
  defp validate_authorization_code(_code), do: {:error, :missing_authorization_code}

  defp secure_equal?(left, right) when byte_size(left) == byte_size(right),
    do: Plug.Crypto.secure_compare(left, right)

  defp secure_equal?(_left, _right), do: false

  defp field(map, key) do
    case Map.fetch(map, key) do
      {:ok, value} -> value
      :error -> Map.get(map, Map.fetch!(@field_atoms, key))
    end
  end

  defp build_url(base_url, query_params) do
    query_string = URI.encode_query(query_params)
    "#{base_url}?#{query_string}"
  end
end
