defmodule Mix.Tasks.Mcp.ApiManifest do
  @moduledoc """
  Writes a deterministic JSON census of the compiled package API under lib/.

      mix mcp.api_manifest --output docs/v2/api_current.json
      mix mcp.api_manifest --source-ref COMMIT --output PATH
      mix mcp.api_manifest --source-ref COMMIT --output PATH --check

  Includes hidden modules/exports, callable macros, callbacks, public/opaque
  types, struct fields and deprecations, following the conservative historical
  API census. Excludes dev/, test/ and dependency modules. Does not start the
  application. An explicit source ref must match the current lib/ tree; without
  one, modified source is marked as a working-tree snapshot.

  --check compares the complete generated bytes with the existing output and
  does not write. Reproduce with the recorded Elixir/OTP toolchain. This census
  does not establish wire or runtime compatibility.
  """

  use Mix.Task

  alias Arbor.MCP.APIManifest

  @shortdoc "Snapshot the package API for a major-version migration"
  @switches [output: :string, source_ref: :string, check: :boolean]

  @impl true
  def run(args) do
    {opts, rest, invalid} = OptionParser.parse(args, strict: @switches)

    if invalid != [] or rest != [] do
      Mix.raise("Invalid arguments: #{inspect(invalid ++ rest)}")
    end

    Mix.Task.run("compile")
    root = File.cwd!()
    output = Path.expand(opts[:output] || "docs/v2/api_current.json", root)
    app = Mix.Project.config()[:app]
    version = Mix.Project.config()[:version]

    app_path = Path.join(Mix.Project.compile_path(), "#{app}.app")
    {:ok, [{:application, ^app, properties}]} = :file.consult(String.to_charlist(app_path))

    manifest =
      APIManifest.build(Keyword.fetch!(properties, :modules),
        root: root,
        application: app,
        version: version,
        environment: Mix.env(),
        source_ref: source_ref(root, opts[:source_ref])
      )

    encoded = APIManifest.encode(manifest)

    if opts[:check] do
      unless File.read(output) == {:ok, encoded} do
        Mix.raise("API manifest differs: #{Path.relative_to(output, root)}")
      end

      Mix.shell().info("API manifest matches #{Path.relative_to(output, root)}")
    else
      File.mkdir_p!(Path.dirname(output))
      File.write!(output, encoded)
      Mix.shell().info("Wrote #{Path.relative_to(output, root)}")
    end

    s = manifest.summary

    Mix.shell().info(
      "#{s.modules} modules, #{s.exports} exports, #{s.macros} macros, " <>
        "#{s.callbacks} callbacks, #{s.types} types, #{s.struct_fields} struct fields"
    )
  end

  defp source_ref(root, requested) do
    commit = resolve_commit(root, requested || "HEAD")
    untracked = untracked_sources?(root)

    if requested && untracked do
      Mix.raise("lib/ has untracked sources; an explicit baseline must match its source ref")
    end

    case System.cmd("git", ["diff", "--quiet", commit, "--", "lib"], cd: root) do
      {_, 0} ->
        snapshot_ref(commit, untracked)

      {_, 1} when is_nil(requested) ->
        snapshot_ref(commit, true)

      {_, 1} ->
        Mix.raise(
          "lib/ differs from #{requested}; snapshot that source tree before freezing its API"
        )

      {_, _} ->
        Mix.raise("Cannot compare lib/ with the requested source ref")
    end
  end

  defp resolve_commit(root, requested) do
    case System.cmd("git", ["rev-parse", "--verify", "#{requested}^{commit}"], cd: root) do
      {commit, 0} -> String.trim(commit)
      {_, _} -> Mix.raise("Cannot resolve source ref #{inspect(requested)}")
    end
  end

  defp untracked_sources?(root) do
    case System.cmd("git", ["ls-files", "--others", "--exclude-standard", "--", "lib"], cd: root) do
      {untracked, 0} -> untracked != ""
      {_, _} -> Mix.raise("Cannot inspect untracked lib/ sources")
    end
  end

  defp snapshot_ref(commit, true), do: commit <> "+working-tree"
  defp snapshot_ref(commit, false), do: commit
end
